version : '3'

services:
    lb:
        image: haproxy
        ports:
            - "8080:8080"
        volumes:
            - ./haproxy:/usr/local/etc/haproxy
    nodeapp1:
        image: microserviceapp
        environment:
            - APPID=1111
    nodeapp2:
        image: microserviceapp
        environment:
            - APPID=2222
    nodeapp3:
        image: microserviceapp
        environment:
            - APPID=3333
    nodeapp4:
        image: microserviceapp
        environment:
            - APPID=4444